export enum PaymentMethod {
    EFECTIVO = 'EFECTIVO',
    TRANSFERENCIA_ELECTRONICA = 'TRANSFERENCIA_ELECTRONICA',
    TARJETA_DE_CREDITO = 'TARJETA_DE_CREDITO',
    TARJETA_DE_DEBITO = 'TARJETA_DE_DEBITO',
    CHEQUE_NOMINATIVO = 'CHEQUE_NOMINATIVO',
}