export enum RegimenFiscal {
    SUELDOS_Y_SALARIOS = 'SUELDOS_Y_SALARIOS',
    RESICO_PERSONAS_FISICAS = 'RESICO_PERSONAS_FISICAS',
    ACTIVIDAD_PROFESIONAL = 'ACTIVIDAD_PROFESIONAL',
    PLATAFORMAS_TECNOLOGICAS = 'PLATAFORMAS_TECNOLOGICAS',
    ARRENDAMIENTO = 'ARRENDAMIENTO',
    INTERESES = 'INTERESES',
}